<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251229183239 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE level (
              id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(2) NOT NULL,
              order_index INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX UNIQ_9AEACC1377153098 ON level (code)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              level_id SMALLINT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8D93D6495FB14BA7 ON "user" (level_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE word (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              latvian VARCHAR(255) NOT NULL,
              russian VARCHAR(255) NOT NULL,
              image_url VARCHAR(255) DEFAULT NULL,
              part_of_speech VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              level_id SMALLINT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C3F175115FB14BA7 ON word (level_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              "user"
            ADD
              CONSTRAINT FK_8D93D6495FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              word
            ADD
              CONSTRAINT FK_C3F175115FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6495FB14BA7');
        $this->addSql('ALTER TABLE word DROP CONSTRAINT FK_C3F175115FB14BA7');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE word');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
